export const CasinoList = [
    "10bet",
    "12bet",
    "888 casino",
    "Bwin", 
    "Betvictor",
    "Betfair",
    "Bet365",
    "Betfed",
    "Pokerstars",
    "Betway",
    "BoyleSports",
    "Coral",
    "Gentingbet",
    "Ladbrokes",
    "Marathon Bet",
    "PaddyPower",
    "Skybet",
    "Unitbet",
    "Leovegas",
    "Play.ee"
]